version: '3'

services:
  db:
    image: postgres
  apptrack:
    image: apptrack
    build: .
    command: /usr/bin/heroku local -p 8000 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
