version: '3'

services:
  db:
    image: postgres:9.6  # Current version on heroku
    environment:
      - POSTGRES_DB=apptrack
      - POSTGRES_PASSWORD=development
  apptrack:
    image: apptrack
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:development@db:5432/apptrack
      - SECRET_KEY=SuperSecret
      - DJANGO_SETTINGS_MODULE=desmond.settings_dev
    # command: /usr/bin/heroku local -p 8000 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
