# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('daytime_phone', models.CharField(max_length=50)),
                ('mobile_phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(blank=True, max_length=50, verbose_name='Current school or school last attended')),
                ('school_address', models.CharField(blank=True, max_length=50, verbose_name="Current or last school's full address")),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Current grade or year if still in school')),
                ('previous_bts', models.TextField(verbose_name='If you have been awarded a BTS scholarship previously, please indicate which scholarship and year.')),
                ('how_heard', models.TextField(verbose_name='How did you hear about the BTS scholarships; e.g., guidance counsellor, scuba instructor, BTS website, etc.?')),
                ('certifications_earned', models.CharField(blank=True, max_length=50)),
                ('certification_agency', models.CharField(blank=True, max_length=50)),
                ('number_of_logged_dives', models.PositiveIntegerField(blank=True, null=True)),
                ('use_of_money', models.TextField(verbose_name='DESCRIBE HOW YOU PLAN TO USE THE SCHOLARSHIP FUNDS AND HOW THIS SCHOLARSHIP WILL HELP YOU TO ACHIEVE YOUR GOALS')),
                ('extra_curriculars', models.TextField(verbose_name='IDENTIFY YOUR EXTRACURRICULAR ACTIVITIES (E.G., SCHOOL RELATED, COMMUNITY RELATED, CLUBS, OTHER.) Be sure to include marine specific activities that you have been involved in, and indicate leadership roles you may have had. Provide dates and/or number of hours of activities.')),
                ('awards', models.TextField(verbose_name='IDENTIFY ANY AWARDS, HONORS OR ACADEMIC ACHIEVEMENTS. Include dates and appropriate information about these awards, etc.')),
                ('work_experience', models.TextField(verbose_name='IDENTIFY ANY INTERNSHIPS/VOLUNTEER/WORK EXPERIENCES YOU HAVE PARTICIPATED IN. Include specific details about these experiences, e.g., dates of the experience, length of time, the work/responsibilities involved, etc.')),
                ('essay', models.TextField(verbose_name='ESSAY: BE SURE TO TELL US ABOUT YOUR INTEREST IN AND PASSION FOR THE OCEANS, THE MARINE LIFE AND ITS PROTECTION AND YOUR MARINE/MARITIME CAREER GOALS.  (Please limit to 500 words.)')),
                ('dive_medic', models.TextField(blank=True, verbose_name='IF YOU ARE APPLYING FOR THE DIVER MEDIC TECHNICIAN SCHOLARSHIP, ALSO COMPOSE A SHORT ESSAY ON "WHY I WANT TO BE A DIVER MEDIC". (Please limit your essay to 250 words.)')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('daytime_phone', models.CharField(max_length=50)),
                ('mobile_phone', models.CharField(blank=True, max_length=50)),
                ('relationship', models.CharField(max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrack.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrack.Scholarship'),
        ),
    ]
