# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number_of_logged_dives',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
