# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrack', '0002_auto_20171017_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dive_medic',
            field=models.TextField(blank=True, verbose_name='IF YOU ARE APPLYING FOR THE DIVER MEDIC TECHNICIAN SCHOLARSHIP, ALSO COMPOSE A SHORT ESSAY ON "WHY I WANT TO BE A DIVER MEDIC". (Please limit your essay to 250 words.)'),
        ),
        migrations.AddField(
            model_name='application',
            name='essay',
            field=models.TextField(default='test', verbose_name='ESSAY: BE SURE TO TELL US ABOUT YOUR INTEREST IN AND PASSION FOR THE OCEANS, THE MARINE LIFE AND ITS PROTECTION AND YOUR MARINE/MARITIME CAREER GOALS.  (Please limit to 500 words.)'),
            preserve_default=False,
        ),
    ]
