# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrack', '0002_recommendationletter_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationletter',
            name='num_years',
            field=models.IntegerField(default=None, verbose_name='Number of years you have known the applicant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendationletter',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recommendationletter',
            name='relationship',
            field=models.CharField(max_length=200, verbose_name='Your relationship with the scholarship applicant (e.g., teacher, counsellor, employer, etc.)'),
        ),
    ]
